package com.citiustech.mrr;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CmmChaseServiceTask implements java.io.Serializable, org.kie.api.runtime.process.WorkItemHandler {

    static final long serialVersionUID = 1L;
    
    private static final String sql = "UPDATE CMM_CHSE_LST SET CMM_CHSE_STS_MSTR_CD = ? , ASSGD_TO_LGN_ID = ? WHERE CMM_ID = ?";

    public CmmChaseServiceTask() {
    }
    
    @Override
    public void executeWorkItem(org.kie.api.runtime.process.WorkItem workItem, org.kie.api.runtime.process.WorkItemManager manager) {
        // extract parameters
        java.util.Map<String, Object> results = new java.util.HashMap<String, Object>();
        com.citiustech.mrr.CMM1 cmmChase = (com.citiustech.mrr.CMM1) workItem.getParameter("cmm");
        System.out.println("[Inside:CmmChaseServiceTask:Expression] [message:CMM Chase Status Master Code is] " + cmmChase.getCmmChseSts());
        System.out.println("[Inside:CmmChaseServiceTask:Expression] [message:New owner name is] " + cmmChase.getAssignToUser());
        System.out.println("[Inside:CmmChaseServiceTask:Expression] [message:CMM ID is] " + cmmChase.getCmmId());
        try (java.sql.Connection conn = com.citiustech.mrr.MRRConnectionUtil.getConnection();java.sql.PreparedStatement stmt = conn.prepareStatement(sql);) {
            stmt.setString(1, cmmChase.getCmmChseSts());
            stmt.setString(2, cmmChase.getAssignToUser());
            stmt.setInt(3, cmmChase.getCmmId().intValue());
            stmt.executeUpdate();
            results.put("cmm", cmmChase);
            manager.completeWorkItem(workItem.getId(), results);
        } catch(java.sql.SQLException ex){
            System.out.println("SQL query execution failed: " + ex);
        }
        
    }

    @Override
    public void abortWorkItem(org.kie.api.runtime.process.WorkItem workItem, org.kie.api.runtime.process.WorkItemManager manager) {
        // Do nothing, notifications cannot be aborted
        System.out.println("--> CmmChaseServiceTask.abortWorkItem()...");
        manager.abortWorkItem(workItem.getId());
    }

}