package com.citiustech.mrr;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MRRConnectionUtil implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    private static final String DATASOURCE_CONTEXT = "java:jboss/datasources/ExampleDS";

    public MRRConnectionUtil() {
    }

    public static java.sql.Connection getConnection() {
        javax.sql.DataSource datasource = null;
        java.sql.Connection conn = null;
        try {
            javax.naming.Context initialContext = new javax.naming.InitialContext();
            datasource = (javax.sql.DataSource)initialContext.lookup(DATASOURCE_CONTEXT);
            conn = datasource.getConnection();
        } catch (javax.naming.NamingException ex) {
            System.out.println("Invalid JNDI connection name: " + ex);
        } catch(java.sql.SQLException ex){
            System.out.println("Unable to create database connection: " + ex);
        }
        return conn;
    }

}